package com.fitquest.app

import com.fitquest.app.data.remote.DailySummaryApiService
import com.fitquest.app.model.DailySummary
import com.fitquest.app.model.MessageResponse
import org.threeten.bp.LocalDate

class FakeDailySummaryService: DailySummaryApiService {
    override suspend fun getDailySummaries(): List<DailySummary> {
        return listOf(DailySummary(date= LocalDate.now()))

    }

    override suspend fun autoGenerateDailySummaries(): MessageResponse {
        return MessageResponse("well")
    }
}