package com.fitquest.app.data.remote

import com.fitquest.app.model.DailySummary
import retrofit2.http.GET
import retrofit2.http.POST

interface DailySummaryApiService {
    @GET("daily-summaries/")
    suspend fun getDailySummaries(): List<DailySummary>

    @POST("daily-summaries/auto-generate/")
    suspend fun autoGenerateDailySummaries()
}