package com.fitquest.app.data.remote

import com.fitquest.app.model.DailySummary
import com.fitquest.app.model.MessageResponse
import retrofit2.http.GET
import retrofit2.http.POST

interface DailySummaryApiService {
    @GET("daily-summaries/")
    suspend fun getDailySummaries(): List<DailySummary>

    @POST("daily-summaries/auto-generate/")
    suspend fun autoGenerateDailySummaries(): MessageResponse
}
