# Generated by Django 5.2.7 on 2025-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_account_groups_account_is_staff_account_is_superuser_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="initial_reps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="last_session_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="account",
            name="total_reps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="total_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="account",
            name="xp",
            field=models.IntegerField(default=0),
        ),
    ]
