# Generated by Django 5.2.4 on 2025-10-19 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_sessions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=50)),
                ('length', models.IntegerField(help_text='Length in minutes')),
                ('previous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_sessions', to='schedule.session')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedule.sport')),
                ('userId', models.ManyToManyField(related_name='sessions', to='schedule.user')),
            ],
        ),
        migrations.CreateModel(
            name='SportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(max_length=50)),
                ('last_practiced', models.DateField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_statuses', to='schedule.session')),
                ('sportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.sport')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_statuses', to='schedule.user')),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='userId',
            field=models.ManyToManyField(related_name='sports', to='schedule.user'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('name', models.CharField(max_length=200)),
                ('isFinished', models.BooleanField(default=False)),
                ('sessionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.session')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.user')),
            ],
        ),
    ]
