# Generated by Django 5.2.7 on 2025-10-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='session',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='sportstatus',
            name='userId',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='isFinished',
            new_name='is_finished',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='sessionId',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='sportstatus',
            old_name='sportId',
            new_name='sport',
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ManyToManyField(default=1, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportstatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sport_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
