# Generated by Django 5.2.7 on 2025-11-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="emoji",
        ),
    ]
