package com.fitquest.app.ui.viewmodels

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.fitquest.app.model.DailyWorkoutItem
import com.fitquest.app.repository.DailySummaryRepository
import com.fitquest.app.repository.ScheduleRepository
import kotlinx.coroutines.launch
import org.threeten.bp.LocalDate
import org.threeten.bp.LocalDateTime
import org.threeten.bp.LocalTime
import org.threeten.bp.ZoneId

class JourneyViewModel(
    private val repository: ScheduleRepository,
    private val dailySummaryRepository: DailySummaryRepository
) : ViewModel() {

    private val _dailyWorkouts = MutableLiveData<List<DailyWorkoutItem>>()
    val dailyWorkouts: LiveData<List<DailyWorkoutItem>> = _dailyWorkouts

    private val _progressState = MutableLiveData<ScheduleProgress>()
    val progressState: LiveData<ScheduleProgress> = _progressState


    fun loadUpcomingSchedules() {
        viewModelScope.launch {
            val now = LocalDateTime.now(ZoneId.of("Asia/Seoul"))
            val schedules = repository.getSchedules()

            val upcoming = schedules.filter {
                val scheduleEnd = LocalDateTime.of(it.scheduledDate, it.endTime)
                val isUpcoming = scheduleEnd.isAfter(now)
                println("Schedule: ${it.scheduledDate} ${it.endTime}, Now: $now, IsUpcoming: $isUpcoming")
                isUpcoming
                scheduleEnd.isAfter(now) || scheduleEnd.isEqual(now)
            }

            val grouped = upcoming.groupBy { it.scheduledDate }

            val dailyItems = grouped.map { (date, scheduleList) ->
                DailyWorkoutItem(
                    date = date,
                    schedules = scheduleList.sortedBy { it.startTime }
                )
            }.sortedBy { it.date }

            _dailyWorkouts.value = dailyItems
        }
    }

    var isInitialized = false

    fun completeScheduleInitFlow() {
        viewModelScope.launch {
            try {
                _progressState.postValue(ScheduleProgress.Step(1, "Processing missed schedules..."))
                repository.markMissedSchedules()

                _progressState.postValue(ScheduleProgress.Step(2, "Generating schedules..."))
                repository.autoGenerateSchedules()

                _progressState.postValue(ScheduleProgress.Step(3, "Generating daily summaries..."))
                dailySummaryRepository.autoGenerateDailySummaries()

                _progressState.postValue(ScheduleProgress.Completed)
            } catch (e: Exception) {
                _progressState.postValue(ScheduleProgress.Error(e.localizedMessage ?: "Unknown error"))
            }
        }
        isInitialized = true
    }
}
