package com.fitquest.app.ui.viewmodels

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.fitquest.app.repository.AuthRepository
import com.fitquest.app.repository.DailySummaryRepository
import com.fitquest.app.repository.ScheduleRepository
import kotlinx.coroutines.launch

/**
 * ViewModel for managing login/signup flow state
 */

sealed class LoginProgress {
    data class Step(val step: Int, val message: String) : LoginProgress()
    object Completed : LoginProgress()
    data class Error(val error: String) : LoginProgress()
}

class LoginViewModel(
    private val scheduleRepository: ScheduleRepository,
    private val dailySummaryRepository: DailySummaryRepository
) : ViewModel() {

    private val _progressState = MutableLiveData<LoginProgress>()
    val progressState: LiveData<LoginProgress> = _progressState

    fun completeLoginFlow() {
        viewModelScope.launch {
            try {
                _progressState.postValue(LoginProgress.Step(1, "Processing missed schedules..."))
                scheduleRepository.markMissedSchedules()

                _progressState.postValue(LoginProgress.Step(2, "Generating schedules..."))
                scheduleRepository.autoGenerateSchedules()

                _progressState.postValue(LoginProgress.Step(3, "Generating daily summaries..."))
                dailySummaryRepository.autoGenerateDailySummaries()

                _progressState.postValue(LoginProgress.Completed)
            } catch (e: Exception) {
                _progressState.postValue(LoginProgress.Error(e.localizedMessage ?: "Unknown error"))
            }
        }
    }
}
