package com.fitquest.app.ui.viewmodels

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.fitquest.app.model.InitProgress
import com.fitquest.app.repository.DailySummaryRepository
import com.fitquest.app.repository.ScheduleRepository
import kotlinx.coroutines.launch

class MainActivityViewModel(
    private val scheduleRepository: ScheduleRepository,
    private val dailySummaryRepository: DailySummaryRepository
) : ViewModel() {

    private val _progressState = MutableLiveData<InitProgress>()
    val progressState: LiveData<InitProgress> = _progressState

    var isInitialized = false
        private set

    fun completeInitFlow() {
        viewModelScope.launch {
            try {
                _progressState.postValue(InitProgress.Step(1, "Processing missed schedules..."))
                scheduleRepository.markMissedSchedules()

                _progressState.postValue(InitProgress.Step(2, "Generating schedules..."))
                scheduleRepository.autoGenerateSchedules()

                _progressState.postValue(InitProgress.Step(3, "Generating daily summaries..."))
                dailySummaryRepository.autoGenerateDailySummaries()

                _progressState.postValue(InitProgress.Completed)
            } catch (e: Exception) {
                _progressState.postValue(InitProgress.Error(e.localizedMessage ?: "Unknown error"))
            }
        }
        isInitialized = true
    }
}
