package com.fitquest.app.repository

import com.fitquest.app.data.remote.DailySummaryApiService
import com.fitquest.app.model.DailySummary
import com.fitquest.app.model.MessageResponse

class DailySummaryRepository(private val service: DailySummaryApiService) {
    suspend fun getDailySummaries(): List<DailySummary> =
        service.getDailySummaries()

    suspend fun autoGenerateDailySummaries(): MessageResponse =
        service.autoGenerateDailySummaries()
}