package com.fitquest.app.repository

import com.fitquest.app.data.remote.DailySummaryApiService
import com.fitquest.app.model.DailySummary

class DailySummaryRepository(private val service: DailySummaryApiService) {
    suspend fun getDailySummaries(): List<DailySummary> =
        service.getDailySummaries()

    suspend fun autoGenerateDailySummaries() =
        service.autoGenerateDailySummaries()
}